#!/usr/bin/env node
// dsh-mobile-bridge: WSS tunnel between the mobile relay and the local dsh web
// (protocol spec: docs/mobile-relay-protocol.md).
//
// The bridge is the dsh adapter: it translates tunnel frames to dsh wire
// envelopes (client-request / client-response / server-request SSE) and back.
// Pairing info is emitted on stdout as single-line JSON events the shell reads.
//
// All remote traffic goes through the relay tunnel (the WebRTC P2P data
// channel was removed — werift no longer ships with the bridge), and phones on
// the same LAN can load the desktop's dsh web directly through the LAN proxy.
//
// Usage: node bridge.mjs --relay wss://relay.example.com --dsh-port 3080
import { randomUUID } from "node:crypto";
import { hostname } from "node:os";
import { parseArgs } from "node:util";
import { createServer, request as httpRequest } from "node:http";
import { gzipSync } from "node:zlib";
import { WebSocketServer } from "ws";

const args = parseArgs({
  options: {
    relay: { type: "string", required: true },
    "dsh-host": { type: "string", default: "127.0.0.1" },
    "dsh-port": { type: "string", default: "3080" },
    "host-name": { type: "string", default: hostname() },
    // 13-digit device ID generated by the shell (from device info). Used as the
    // host ID on the relay; the shell embeds it in the pairing QR code.
    "device-id": { type: "string", default: "" },
    // Stable pairing PIN chosen by the shell (persisted; editable in Settings).
    // When provided the relay keeps it as the host's long-lived PIN.
    pin: { type: "string", default: "" },
    // Persisted hostToken from a previous registration (shell stores it in
    // UserDefaults). Lets a bridge restart reconnect by token instead of
    // re-registering anonymously — the relay refuses anonymous re-registration
    // of an existing hostId (hijack protection).
    "host-token": { type: "string", default: "" },
    // LAN direct-connect port: the phone prefers loading the dsh web straight
    // from this machine when it can reach it, and falls back to the relay.
    "lan-port": { type: "string", default: "13080" },
  },
});
const RELAY = (() => {
  let r = args.values.relay.replace(/\/$/, "");
  // Accept https://relay.example.com (as stored by the shell Settings… dialog)
  // or a bare host:port; Node's built-in WebSocket only accepts ws://wss://.
  // ws:// must pass through untouched — prefixing it produced `wss://ws://…`,
  // which fails silently forever (self-hosted LAN relays hit exactly this).
  if (r.startsWith("https://")) r = "wss://" + r.slice("https://".length);
  else if (r.startsWith("http://")) r = "ws://" + r.slice("http://".length);
  else if (!r.startsWith("ws://") && !r.startsWith("wss://")) r = "wss://" + r;
  return r;
})();
const DSH_BASE = `http://${args.values["dsh-host"]}:${args.values["dsh-port"]}`;
const HOST_NAME = args.values["host-name"];
const DEVICE_ID = args.values["device-id"] || "";
// Seed the in-memory hostToken from the shell-persisted one, so a restart
// reconnects with `Authorization: Bearer` instead of re-registering.
let hostToken = args.values["host-token"] || null;

// ---- single-instance guard ------------------------------------------------
// The shell re-spawns the bridge after an unexpected exit (auto-restart), and
// a killed parent app can leave orphaned bridge processes behind. Multiple
// bridges for the same device id fight over the relay registration (each
// replaces / refuses the other) and end up leaving the host offline. Kill any
// older bridge for this device id before connecting.
{
  try {
    const { execFileSync } = await import("node:child_process");
    const out = execFileSync("pgrep", ["-f", `bridge\\.mjs.*--device-id ${DEVICE_ID}`], {
      encoding: "utf8",
    });
    const me = process.pid;
    for (const pidStr of out.trim().split(/\s+/)) {
      const pid = parseInt(pidStr, 10);
      if (pid && pid !== me) {
        try {
          process.kill(pid, "SIGKILL");
          console.log(JSON.stringify({ event: "replaced-stale-bridge", pid }));
        } catch {
          /* already gone */
        }
      }
    }
  } catch {
    /* pgrep unavailable or no stale bridges — fine */
  }
}

// ---- LAN direct-connect proxy ----------------------------------------------
// dsh web binds 127.0.0.1, so a phone on the same LAN can't load it directly.
// Listen on 0.0.0.0:<lan-port> and forward to the local dsh web, stripping
// Origin/Host so dsh's origin check passes. The phone prefers this path and
// falls back to the relay tunnel when it can't reach it.
const DSH_PORT = Number(args.values["dsh-port"]);
const LAN_PORT = Number(args.values["lan-port"]) || 13080;

function stripForwardHeaders(headers) {
  const h = { ...headers };
  delete h.origin;
  delete h.host;
  delete h.connection;
  delete h.upgrade;
  delete h["keep-alive"];
  delete h["proxy-connection"];
  return h;
}

const lanServer = createServer((req, res) => {
  const fwd = httpRequest(
    {
      host: "127.0.0.1",
      port: DSH_PORT,
      method: req.method,
      path: req.url,
      headers: stripForwardHeaders(req.headers),
    },
    (fres) => {
      const h = { ...fres.headers };
      delete h["transfer-encoding"];
      delete h.connection;
      res.writeHead(fres.statusCode ?? 502, h);
      fres.pipe(res);
    }
  );
  fwd.on("error", () => {
    if (!res.headersSent) res.writeHead(502, { "content-type": "text/plain" });
    res.end("desktop dsh offline");
  });
  req.pipe(fwd);
});

const lanWss = new WebSocketServer({ server: lanServer });
lanWss.on("connection", (client, req) => {
  const path = (req.url || "/").split("?")[0];
  if (!path.startsWith("/api/events.") && path !== "/plugins/events") {
    client.close(1008, "not allowed");
    return;
  }
  if (path === "/plugins/events") {
    // HTTP SSE endpoint streamed over the phone's WebSocket: fetch dsh and
    // forward each chunk as a WS message so the phone's proxy can write it
    // into the WebView response (a plain HTTP request would stall forever).
    const ctl = new AbortController();
    client.on("close", () => ctl.abort());
    client.on("error", () => ctl.abort());
    fetch(`${DSH_BASE}${req.url || ""}`, { signal: ctl.signal })
      .then(async (resp) => {
        if (!resp.ok || !resp.body) {
          try { client.close(1011, "upstream failed"); } catch { /* ignore */ }
          return;
        }
        const reader = resp.body.getReader();
        const decoder = new TextDecoder();
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;
          const text = decoder.decode(value, { stream: true });
          if (text && client.readyState === 1) client.send(text);
        }
        try { client.close(); } catch { /* ignore */ }
      })
      .catch(() => { try { client.close(1011, "upstream failed"); } catch { /* ignore */ } });
    return;
  }
  const wsUrl = DSH_BASE.replace(/^http/, "ws") + (req.url || "");
  let up;
  try {
    // No forwarded headers: dsh accepts origin-less WS and the LAN proxy is
    // unauthenticated. Forwarding sec-websocket-* breaks the built-in
    // WebSocket's own upgrade handshake.
    up = new WebSocket(wsUrl);
  } catch {
    client.close(1011);
    return;
  }
  // `up` is Node's built-in WebSocket (no `.on()`); use property handlers.
  up.binaryType = "arraybuffer";
  up.onopen = () => {
    up.onmessage = (ev) => {
      if (client.readyState !== 1) return;
      if (typeof ev.data === "string") client.send(ev.data);
      else client.send(Buffer.from(ev.data));
    };
    client.on("message", (d, isBinary) => {
      if (up.readyState === 1) up.send(d, { binary: isBinary });
    });
    up.onclose = () => { try { client.close(); } catch { /* ignore */ } };
    client.on("close", () => { try { up.close(); } catch { /* ignore */ } });
    client.on("error", () => { try { up.close(); } catch { /* ignore */ } });
    up.onerror = () => { try { client.close(1011, "upstream failed"); } catch { /* ignore */ } };
  };
  up.onerror = () => { try { client.close(1011, "upstream failed"); } catch { /* ignore */ } };
});

lanServer.listen(LAN_PORT, "0.0.0.0", () => {
  console.log(JSON.stringify({ event: "lan-ready", port: LAN_PORT }));
});

let ws = null;
let hostId = null;
let registered = false;
let backoff = 1000;
let sseStreams = new Map(); // channel -> AbortController

// ---- stdout event lines (consumed by the shell) ----
function emit(event, extra = {}) {
  console.log(JSON.stringify({ event, ...extra }));
}

// ---- relay tunnel ----
function tunnelUrl() {
  return new URL("/relay/v1/host", RELAY);
}

// Last time any frame arrived from the relay. A dead TCP half-open would
// otherwise never fire onclose and the host would stay "offline" forever.
let lastSeen = Date.now();
setInterval(() => {
  if (ws && Date.now() - lastSeen > 45000) {
    // Relay sends a ping every 30s; 45s of silence means the link is dead —
    // force-close so onclose runs and the reconnect loop kicks in.
    try { ws.close(); } catch { /* ignore */ }
  }
}, 15000);

function connect() {
  const headers = hostToken ? { Authorization: `Bearer ${hostToken}` } : undefined;
  ws = new WebSocket(tunnelUrl(), headers ? { headers } : undefined);
  ws.onopen = () => {
    backoff = 1000;
    if (!hostToken) {
      // First connection: register (the relay answers with hostToken + pair info).
      sendRegister();
    } else {
      emit("online");
    }
  };
  ws.onmessage = (ev) => {
    lastSeen = Date.now();
    let frame;
    try { frame = JSON.parse(ev.data); } catch { return; }
    if (frame.type === "ping") { ws.send(JSON.stringify({ v: 1, type: "pong" })); return; }
    if (frame.type === "control") { handleControl(frame); return; }
    switch (frame.type) {
      case "rpc": handleRpc(frame); break;
      case "http": handleHttp(frame); break;
      case "sse-open": handleSseOpen(frame); break;
      case "sse-close": handleSseClose(frame); break;
      case "respond": handleRespond(frame); break;
      default: /* ignore */ break;
    }
  };
  ws.onclose = () => {
    if (registered) emit("offline");
    sseStreams.forEach((ctl) => ctl.abort());
    sseStreams.clear();
    setTimeout(connect, backoff);
    // Cap low (10s): with token takeover on the relay a refused reconnect is
    // rare, and a short cap turns a relay restart / network blip into a
    // second-scale outage instead of a minute-long one.
    backoff = Math.min(backoff * 2, 10000);
  };
  ws.onerror = () => {
    // A pre-registration connect failure used to be completely silent (this
    // is how the wss://-prefix bug above hid for so long). The shell just
    // logs unknown events, so emit one.
    if (!registered) emit("relay-unreachable", { relay: RELAY });
  };
}

function sendRegister() {
  ws.send(JSON.stringify({
    v: 1, type: "control", kind: "register",
    body: {
      hostId: DEVICE_ID, hostName: HOST_NAME,
      dshVersion: process.env.DSH_VERSION || "unknown",
      // Present on re-registration after a relay restart: proves we are the
      // original owner of this hostId (relay rejects existing hosts otherwise).
      ...(hostToken ? { token: hostToken } : {}),
      ...(args.values.pin ? { pin: args.values.pin } : {}),
    },
  }));
}

function handleControl(frame) {
  if (frame.kind === "registered") {
    const p = frame.body || {};
    hostToken = p.hostToken;
    hostId = p.hostId;
    registered = true;
    // The shell generates the pairing QR code itself (relay host + device ID);
    // it only needs the PIN the relay issued. The hostToken is emitted too so
    // the shell can query the relay for connected devices (see host/devices).
    emit("registered", {
      hostId: p.hostId, hostToken: p.hostToken,
      pin: p.pin, pinExpiresAt: p.pinExpiresAt,
    });
  } else if (frame.kind === "unknown-host") {
    // Relay restarted and lost our host: re-register under the same hostId.
    sendRegister();
  }
}

function send(frame) {
  if (ws && ws.readyState === WebSocket.OPEN) ws.send(JSON.stringify(frame));
}

function rpcError(channel, rpcId, code, message) {
  send({ v: 1, type: "rpc-reply", channel, rpcId, body: { ok: false, error: { code, message, transport: true } } });
}

// ---- RPC: POST /api/<method> with dsh client-request envelope ----
async function handleRpc(frame) {
  const method = frame.path.replace(/^\/api\//, "");
  const dshRpcId = randomUUID();
  const started = Date.now();
  try {
    const resp = await fetch(`${DSH_BASE}/api/${method}`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ type: "client-request", rpcId: dshRpcId, method, payload: frame.body ?? {} }),
      signal: AbortSignal.timeout(20000),
    });
    const json = await resp.json();
    const items = Array.isArray(json?.result?.value?.items) ? json.result.value.items.length : "?";
    emit("dsh-rpc", { method, status: resp.status, ms: Date.now() - started, items });
    send({ v: 1, type: "rpc-reply", channel: frame.channel, rpcId: frame.rpcId, body: json.result });
  } catch (err) {
    emit("dsh-rpc-error", { method, error: String(err?.message || err) });
    rpcError(frame.channel, frame.rpcId, "dsh-unreachable", String(err?.message || err));
  }
}

// ---- Generic HTTP proxy: the phone's WebView talks to dsh through this ----
// Frames: http {id, channel, method, path, body:{headers?, body(base64)?}}
//        http-reply {id, channel, status, body:{headers?, body(b64), part?}}
// Large replies are sent as several `part` frames (~256 KiB of base64 each)
// instead of one giant JSON text frame: the relay and phone reassemble them,
// a transfer can no longer blow the frame size limits of intermediaries, and
// the phone's idle-based timeout sees progress while chunks keep arriving.
// part = {index, total}; part[0] carries the headers; an `abort` field marks
// a transfer that failed midway (receiver answers 502 to the page).

// Raw bytes per part (base64 inflates by ~4/3 → ~256 KiB frames).
const REPLY_CHUNK = 192 * 1024;

function wsOpen() {
  return ws && ws.readyState === WebSocket.OPEN;
}

// The built-in WebSocket buffers unboundedly; on a slow relay downlink a
// multi-MB reply must not all sit in memory at once. Wait until the socket
// has drained below ~1 MiB before queueing the next chunk.
function waitDrain() {
  return new Promise((resolve) => {
    const check = () => {
      if (!wsOpen() || (ws.bufferedAmount || 0) < 1 << 20) resolve();
      else setTimeout(check, 25);
    };
    check();
  });
}

async function handleHttp(frame) {
  const bodyObj = frame.body && typeof frame.body === "object" ? frame.body : {};
  const headers = {};
  for (const [k, v] of Object.entries(bodyObj.headers || {})) headers[k] = v;
  const resp = await proxyHttp(frame.method || "GET", frame.path, headers, bodyObj.body);
  const buf = resp.body;
  const total = Math.max(1, Math.ceil(buf.length / REPLY_CHUNK));
  try {
    for (let i = 0; i < total; i++) {
      if (!wsOpen()) return;
      const part = {
        v: 1, type: "http-reply", channel: frame.channel, id: frame.id, status: resp.status,
        body: {
          ...(i === 0 ? { headers: resp.headers } : {}),
          body: buf.subarray(i * REPLY_CHUNK, (i + 1) * REPLY_CHUNK).toString("base64"),
          part: { index: i, total },
        },
      };
      send(part);
      if (i < total - 1) await waitDrain();
    }
  } catch (err) {
    if (wsOpen()) {
      send({
        v: 1, type: "http-reply", channel: frame.channel, id: frame.id, status: 502,
        body: { body: Buffer.from(String(err?.message || err)).toString("base64"), abort: true },
      });
    }
  }
}

/// Proxy one HTTP request to the local dsh web (used by the relay tunnel).
/// Returns {status, headers, body: Buffer} — chunking happens in handleHttp.
async function proxyHttp(method, path, headers, bodyBase64) {
  const init = { method, headers: headers || {}, signal: AbortSignal.timeout(20000) };
  if (bodyBase64 != null && bodyBase64 !== "") {
    init.body = Buffer.from(bodyBase64, "base64");
  }
  try {
    const resp = await fetch(`${DSH_BASE}${path}`, init);
    const buf = Buffer.from(await resp.arrayBuffer());
    const replyHeaders = {};
    const ct = resp.headers.get("content-type");
    if (ct) replyHeaders["content-type"] = ct;
    const loc = resp.headers.get("location");
    if (loc) replyHeaders.location = loc;
    // The relay downlink (server -> phone) is often bandwidth-starved
    // (e.g. a 1 Mbps egress cap); compress large bodies so the phone's
    // WebView (which decodes content-encoding itself) receives far fewer
    // bytes. Skip tiny payloads and already-compressed responses.
    if (buf.length > 2048 && !/^image\//.test(ct || "") && buf.length > 0 &&
        !replyHeaders["content-encoding"]) {
      const gz = gzipSync(buf, { level: 6 });
      if (gz.length < buf.length * 0.9) {
        replyHeaders["content-encoding"] = "gzip";
        return { status: resp.status, headers: replyHeaders, body: gz };
      }
    }
    return { status: resp.status, headers: replyHeaders, body: buf };
  } catch (err) {
    return {
      status: 502,
      headers: { "content-type": "text/plain" },
      body: Buffer.from(String(err?.message || err)),
    };
  }
}

// ---- SSE/WS: /api/events.mux|host ----
// Two modes:
//  - raw:true — forward each server frame verbatim. The phone's WebView
//    connects to /api/events.mux with a real WebSocket (downlink-only), so
//    the bridge mirrors that with its own WebSocket to dsh.
//  - default — translate server-request frames to the narrow {rpcId, method,
//    payload} form the native app consumes (fetch-based SSE fallback).
async function handleSseOpen(frame) {
  const raw = frame.body?.raw === true;
  if (raw) {
    if (frame.path === "/api/events.mux" || frame.path === "/api/events.host") {
      const wsUrl = DSH_BASE.replace(/^http/, "ws") + frame.path;
      let dshWs;
      try {
        dshWs = new WebSocket(wsUrl);
      } catch (err) {
        send({ v: 1, type: "sse-close", channel: frame.channel, body: { reason: "error" } });
        return;
      }
      sseStreams.set(frame.channel, dshWs);
      dshWs.onmessage = (ev) => {
        if (typeof ev.data === "string") {
          send({ v: 1, type: "sse-frame", channel: frame.channel, body: { data: ev.data } });
        }
      };
      dshWs.onclose = () => {
        send({ v: 1, type: "sse-close", channel: frame.channel, body: { reason: "eof" } });
        sseStreams.delete(frame.channel);
      };
      dshWs.onerror = () => { /* onclose follows */ };
      return;
    }
    // Other raw paths (e.g. /plugins/events) are HTTP SSE streams, not
    // WebSockets: fetch and forward each chunk verbatim so the phone's proxy
    // can stream them into the WebView response instead of buffering until
    // the never-ending stream times out (a 30s stall on every connect).
    const ctl = new AbortController();
    sseStreams.set(frame.channel, ctl);
    try {
      const resp = await fetch(`${DSH_BASE}${frame.path}`, { signal: ctl.signal });
      if (!resp.ok || !resp.body) {
        send({ v: 1, type: "sse-close", channel: frame.channel, body: { reason: "error" } });
        return;
      }
      const reader = resp.body.getReader();
      const decoder = new TextDecoder();
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        const text = decoder.decode(value, { stream: true });
        if (text) {
          send({ v: 1, type: "sse-frame", channel: frame.channel, body: { data: text } });
        }
      }
      send({ v: 1, type: "sse-close", channel: frame.channel, body: { reason: "eof" } });
    } catch (err) {
      if (err?.name !== "AbortError") {
        send({ v: 1, type: "sse-close", channel: frame.channel, body: { reason: "error" } });
      }
    } finally {
      sseStreams.delete(frame.channel);
    }
    return;
  }
  const ctl = new AbortController();
  sseStreams.set(frame.channel, ctl);
  try {
    const resp = await fetch(`${DSH_BASE}${frame.path}`, { signal: ctl.signal });
    if (!resp.ok || !resp.body) {
      send({ v: 1, type: "sse-close", channel: frame.channel, body: { reason: "error" } });
      return;
    }
    const reader = resp.body.getReader();
    const decoder = new TextDecoder();
    let buffer = "";
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      let boundary;
      while ((boundary = buffer.indexOf("\n\n")) !== -1) {
        const chunk = buffer.slice(0, boundary);
        buffer = buffer.slice(boundary + 2);
        const data = chunk.split("\n").filter((l) => l.startsWith("data: ")).map((l) => l.slice(6)).join("");
        if (!data) continue;
        let full;
        try { full = JSON.parse(data); } catch { continue; }
        send({
          v: 1, type: "sse-frame", channel: frame.channel,
          body: { rpcId: full.rpcId, method: full.method, payload: full.payload },
        });
      }
    }
    send({ v: 1, type: "sse-close", channel: frame.channel, body: { reason: "eof" } });
  } catch (err) {
    if (err?.name !== "AbortError") {
      send({ v: 1, type: "sse-close", channel: frame.channel, body: { reason: "error" } });
    }
  } finally {
    sseStreams.delete(frame.channel);
  }
}

function handleSseClose(frame) {
  const ctl = sseStreams.get(frame.channel);
  if (ctl) {
    if (typeof ctl.abort === "function") ctl.abort();
    else if (typeof ctl.close === "function") ctl.close();
  }
  sseStreams.delete(frame.channel);
}

// ---- Respond: POST /api/respond with dsh client-response envelope ----
async function handleRespond(frame) {
  try {
    const resp = await fetch(`${DSH_BASE}/api/respond`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ type: "client-response", rpcId: frame.rpcId, result: frame.body ?? { ok: true, value: {} } }),
    });
    const json = await resp.json();
    send({ v: 1, type: "rpc-reply", channel: frame.channel, rpcId: frame.rpcId, body: { ok: true, value: json } });
  } catch (err) {
    rpcError(frame.channel, frame.rpcId, "dsh-unreachable", String(err?.message || err));
  }
}

connect();
